import React, { useEffect } from 'react';
import CRMStudentHeader from './StudentHeader.jsx';
import CRMMetrics from './Metrics.jsx';
import StudentProfileOverview from './StudentProfileOverview.jsx';
import AIReportCRMView from './Report.jsx';
import PrevTechCourses from './PrevTechCourses.jsx';
import Inquiries from './Inquiries.jsx';

const StudentDetailPage = ({ student: propStudent, onBack: propOnBack }) => {
  useEffect(
    () => {
      window.scrollTo(0, 0);
    }, []
  );
  const defaultStudent = {
    student_id: 'kV4sSGNv31Mtkv0LR0uBqh6q11s1',
    fullName: 'Kenny Giwa',
    email: 'kennyhg@gmail.com',
    phoneNumber: '376788978998789',
    age: '18-24',
    country: 'Albania',
    tier: 1,
    leadScore: 20,
    hasOnboarded: true,
    createdAt: new Date('2025-10-29T18:12:16Z'),
    reportGeneratedAt: new Date('2025-11-01T08:23:12Z'),
    onboardingAnswers: {
      achieve: 'explore',
      age: '18-24',
      area: 'frontend',
      availability: 'part-time',
      comfortRating: '2',
      fullName: 'Kenny Giwa',
      haveTakenTechCourses: 'no',
      learningStyle: 'reading',
      occupation: 'Graduate',
      preferredChannel: 'video',
      projectEnjoyed: 'hjhj'
    },
    reportText: {
      compliance_info: {
        conversion_tracking_id: 'CT12345',
        watermark_text: 'Generated by Catalyst System'
      },
      report_type: 'My Path Snapshot (Tier 1 Lead Magnet)',
      snapshot_data: {
        current_level: 'Beginner',
        match_justification: 'Based on your interest and preferred learning style, frontend development is a great fit.',
        primary_match_field: 'frontend',
        top_course_match: 'Introduction to Web Development'
      },
      viral_cta: {
        benefits: [
          'Personalized Career Path',
          'Expert 1:1 Mentorship',
          'Exclusive Project Portfolio'
        ],
        heading: 'Unlock Your Full Potential!',
        link_text: 'Get the Premium Plan'
      }
    }
  };
  const student = propStudent || defaultStudent;

  const handleBack = () => {
  if (propOnBack) {
    propOnBack();
  } else {
    console.log('Navigate back to students list');
    alert('Navigating back to students list...');
  }
};

  return (
    <div className="min-h-screen bg-gray-50">
      <CRMStudentHeader student={student} onBack={handleBack} />

      <div className="max-w-7xl mx-auto px-6 py-6 space-y-6">
        <CRMMetrics student={student} />
        
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div className="space-y-6">
            <StudentProfileOverview 
              student={student} 
              onboardingAnswers={student.onboardingAnswers} 
            />
            {/* <AdvisorNotes /> */}
          </div>
          <div className="space-y-6">
            <Inquiries inquiries={student.inquiries} />
          </div>
          <div className="space-y-6">
            <PrevTechCourses student={student} />
          </div>
          <div>
            <AIReportCRMView reportText={student.reportText} />
          </div>
        </div>
      </div>
    </div>
  );
};

export default StudentDetailPage;